### ISSUE TITLE
Document Type static as "cpf"

### ISSUE THREAD

**Issue by JoelsonFerreira** [vtex-apps/storefront-permissions#102]
**Describe the bug**
In the file "storefront-permissions\node\resolvers\Routes\index.ts" there is a field PROFILE_DOCUMENT_TYPE: 'cpf'. There are stores that are not from Brazil and use this APP. In Colombia, for example, this field should be cedulaCOL. This causes a bug when finalizing payments.

**To Reproduce**

1. Go to '/checkout'
2. Check documentType in orderForm: 'vtexjs.checkout,orderForm.clientProfileData.documentType'

**Expected behavior**
Document Type must have its value according to the country's document type.

**Comment by JoelsonFerreira** [comment]
@arturmagalhaesjr could you check that please?

**Comment by enzomerca** [comment]
Right now there is no easy way to define the proper documentType according to the country.
So for now, we fixed this by only setting documentType to CPF if the country is Brazil, otherwise we don't touch it.

Please re-open this bug if it still an issue for you.

Thanks!
