### ISSUE TITLE
Error when client has not phone or homePhone optional fields

### ISSUE THREAD

**Issue by tiago-freire** [vtex-apps/storefront-permissions#110]
**Describe the bug**

Changes of commit 21279a2ccb8a6483c1106cc44e6cb373880d57b7 introduced a bug because `phone` and `homePhone` are optional client fields.

So the initialization of `phoneNumberFormatted` should be inside `if (clUser && orderFormId) { ... }`.

Otherwise, a `TypeError: Cannot read property 'phone' of null` is being thrown on backend when a user has no registered phone.

Due to the recent degradation of github actions, I preferred to report a bug instead of opening a PR to seek faster resolution.

**Solution suggestion**

```diff
-  const phoneNumberFormatted =
-    phoneNumber || clUser.phone || clUser.homePhone || `+1${'0'.repeat(10)}`

    if (clUser && orderFormId) {
+    const phoneNumberFormatted =
+      phoneNumber || clUser.phone || clUser.homePhone || `+1${'0'.repeat(10)}`
    ...
  }
```

**To Reproduce**

1. Go to a B2B admin where you have a registered client organization
2. Delete the phone fields of a client at /admin/customers
3. Try to logon
4. See that you will not be able to enter the "authenticated" state

Additional step:

- Link storefront-permissions app in order to view backend logs. You should see error below:
```
error: [node-vtex-api error] TypeError: Cannot read property 'phone' of null
    at setProfile (/usr/src/node/resolvers/Routes/index.ts:552:29)
```

**Comment by mairatma** [comment]
@tiago-freire I've just deployed a new version of store-permissions with this change. Once your store is upgraded to `vtex.storefront-permissions@1.34.1`, can you verify this is fixed on your side? Thanks again for reporting!

**Comment by tiago-freire** [comment]
@mairatma works perfectly now! thanks
